name: Run test case

on: [push, pull_request]

jobs:
    run_test_case:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash

        strategy:
          matrix:
            os:
              - ubuntu20.04
            otp:
              - 24.2.1-1
            elixir:
              - 1.13.3
            arch:
              - amd64

        container:
            image: ghcr.io/emqx/emqx-builder/5.0-8:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}

        steps:
        - uses: actions/checkout@v2

        - name: Install prerequisites
          run: |
            apt update
            apt install -y cmake gnupg iproute2
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
              focal stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt update && apt install -y docker-ce docker-ce-cli containerd.io

        - name: run etcd container
          run: |
            HostIP=172.17.0.1
            docker run -d -v /usr/share/ca-certificates/:/etc/ssl/certs:ro \
              -p 4001:4001 -p 2380:2380 -p 2379:2379 \
              --name etcd0 \
              gcr.io/etcd-development/etcd:latest etcd \
              -name etcd0 \
              -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001 \
              -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
              -initial-advertise-peer-urls http://${HostIP}:2380 \
              -listen-peer-urls http://0.0.0.0:2380 \
              -initial-cluster-token etcd-cluster-1 \
              -initial-cluster etcd0=http://${HostIP}:2380 \
              -initial-cluster-state new

        - name: Check versions
          run: |
            ./git-tag.sh dummy --dryrun

        - name: Get deps git refs for cache
          id: deps-refs
          run: |
            scripts/get-dep-refs.sh

        - name: load rocksdb cache
          uses: actions/cache@v2
          with:
            path: |
              _build/default/lib/rocksdb/
            key: ${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.arch }}-${{ steps.deps-refs.outputs.DEP_ROCKSDB_REF }}

        - name: Run tests
          run: |
            docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' etcd0
            docker inspect etcd0
            docker ps
            docker logs etcd0
            export ETCD_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' etcd0)
            echo etcd running at $ETCD_HOST:2379
            curl -v http://$ETCD_HOST:2379 || true
            make eunit
            make ct
            make cover
        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
